encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("new", views.newPage, name="new"),
    path("random", views.random, name="random"),
    path("<str:entry>", views.page, name="page"),
    path("<str:entry>/edit", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls", namespace='wiki'))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms

import markdown2
from random import choice
from . import util

class SearchForm(forms.Form):
  search = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Search Wiki'}))

searchForm = SearchForm(auto_id=True)

class NewPageForm(forms.Form):
  title = forms.CharField()
  markdown = forms.CharField(widget=forms.Textarea)

def index(request):
  if request.method == "POST":
    form = NewPageForm(request.POST)

    if form.is_valid():
      form = form.cleaned_data
      title = form["title"]
      print(form)
      markdown = form["markdown"]
      util.save_entry(title, markdown)

    return render(request, "encyclopedia/index.html", {
      "entries": util.list_entries(),
      "searchbox": searchForm
    })
  else:
    return render(request, "encyclopedia/index.html", {
      "entries": util.list_entries(),
      "searchbox": searchForm
    })

def page(request, entry):
  page = util.get_entry(entry)
  if page is None:
    return render(request, "encyclopedia/error.html", {
      "error": "Page Does Not Exist",
      "message": "This page could not be found",
      "searchbox": searchForm
    })
  else:
    return render(request, "encyclopedia/page.html", {
      "page": markdown2.markdown(page),
      "title": entry,
      "searchbox": searchForm
    })

def search(request):
  if request.method == "POST":
    form = SearchForm(request.POST)

    if form.is_valid():
      search = form.cleaned_data["search"]
      entries = util.get_entry(search)

      if entries == None:
        p = list()
        entries = util.list_entries()
        for entry in entries:
          if search.lower() in entry.lower():
            p.append(entry)

        p.sort()
        entries = p
        return render(request, "encyclopedia/searchresults.html", {
        "query": search,
        "entries": entries,
        "searchbox": searchForm
        })
      else:
        return HttpResponseRedirect(reverse("wiki:page", kwargs={"entry": search}))
    else:
      return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "searchbox": searchForm
      })

def newPage(request):
  newForm = NewPageForm(auto_id=True)

  return render(request, "encyclopedia/new.html", {
    "searchbox": searchForm,
    "form": newForm
  })

def edit(request, entry):
  markdown = util.get_entry(entry)
  page = markdown2.markdown(markdown)
  if request.method == "GET":
    editForm = NewPageForm({
      'markdown': markdown,
      'title': entry
    })

    if editForm.is_valid():
      editForm.markdown = markdown
      
      return render(request, "encyclopedia/edit.html", {
          "edit": editForm,
          "title": entry,
          "searchbox": searchForm
        })
    else: 
      return render(request, "encyclopedia/page.html", {
        "page": markdown2.markdown(page),
        "title": entry,
        "searchbox": searchForm
      })

def random(request):
  entries_list = util.list_entries()
  rand_entry = choice(entries_list)

  return HttpResponseRedirect(reverse("wiki:page", kwargs={"entry": rand_entry}))

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title|safe }}
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
  <form class="edit" action="{% url 'wiki:index' %}" method="post">
    {% csrf_token %}
    {% for field in edit %}
      <div class="{{ field.name }}">
        <div class="lbl_{{ field.name}}">
          <label for="{{ field.name }}">{{ field.name }}:</label>
        </div>
        {{ field|safe }}
      </div>
    {% endfor %}
    <div>
      <input type="submit">
    </div>
  </form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    404 Page Not Found
{% endblock %}

{% block body %}
    <div class="error">
        <h1>404</h1>
        <p>{{ message }}</p>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul class="entry-list">
        {% for entry in entries %}
            <li >
                <a href="{% url 'wiki:page' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form class="search" action="{% url 'wiki:search' %}" method="post">
                    {% csrf_token %}
                    {{ searchbox }}
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title|safe }}
{% endblock %}

{% block body %}
    <div>
      <form class="edit" action="{% url 'wiki:index' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="{{ field.name }}">
            <div class="lbl_{{ field.name }}">
              <label for="{{ field.name }}">{{ field.name }}:</label>
            </div>
            {{ field|safe }}
          </div>
        {% endfor %}
        <div>
          <input type="submit">
        </div>
      </form>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title|safe }}
{% endblock %}

{% block nav %}
  <div>
    <a href="{% url 'wiki:edit' title %}">Edit Entry</a>
  </div>
{% endblock %}

{% block body %}
  <div>
    {{ page|safe }}
  </div>
{% endblock %}

encyclopedia/templates/encyclopedia/searchresults.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div>
        <h1>Results for: {{ query|safe }}</h1>
        <ul class="entry-list">
          {% for entry in entries %}
            <li >
              <a href="{% url 'wiki:page' entry %}">{{ entry }}</a>
            </li>
          {% endfor %}
        </ul>
    </div>
{% endblock %}